// Code generated by ent, DO NOT EDIT.

package hlsartifact

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the hlsartifact type in the database.
	Label = "hls_artifact"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSourceFileID holds the string denoting the source_file_id field in the database.
	FieldSourceFileID = "source_file_id"
	// FieldStoragePath holds the string denoting the storage_path field in the database.
	FieldStoragePath = "storage_path"
	// FieldSegmentCount holds the string denoting the segment_count field in the database.
	FieldSegmentCount = "segment_count"
	// FieldTotalSize holds the string denoting the total_size field in the database.
	FieldTotalSize = "total_size"
	// FieldCodec holds the string denoting the codec field in the database.
	FieldCodec = "codec"
	// EdgeSourceFile holds the string denoting the source_file edge name in mutations.
	EdgeSourceFile = "source_file"
	// Table holds the table name of the hlsartifact in the database.
	Table = "hls_artifacts"
	// SourceFileTable is the table that holds the source_file relation/edge.
	SourceFileTable = "hls_artifacts"
	// SourceFileInverseTable is the table name for the File entity.
	// It exists in this package in order to avoid circular dependency with the "file" package.
	SourceFileInverseTable = "files"
	// SourceFileColumn is the table column denoting the source_file relation/edge.
	SourceFileColumn = "source_file_id"
)

// Columns holds all SQL columns for hlsartifact fields.
var Columns = []string{
	FieldID,
	FieldSourceFileID,
	FieldStoragePath,
	FieldSegmentCount,
	FieldTotalSize,
	FieldCodec,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSegmentCount holds the default value on creation for the "segment_count" field.
	DefaultSegmentCount int
	// DefaultTotalSize holds the default value on creation for the "total_size" field.
	DefaultTotalSize int64
	// DefaultCodec holds the default value on creation for the "codec" field.
	DefaultCodec string
)

// OrderOption defines the ordering options for the HLSArtifact queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySourceFileID orders the results by the source_file_id field.
func BySourceFileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceFileID, opts...).ToFunc()
}

// ByStoragePath orders the results by the storage_path field.
func ByStoragePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStoragePath, opts...).ToFunc()
}

// BySegmentCount orders the results by the segment_count field.
func BySegmentCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSegmentCount, opts...).ToFunc()
}

// ByTotalSize orders the results by the total_size field.
func ByTotalSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalSize, opts...).ToFunc()
}

// ByCodec orders the results by the codec field.
func ByCodec(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodec, opts...).ToFunc()
}

// BySourceFileField orders the results by source_file field.
func BySourceFileField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSourceFileStep(), sql.OrderByField(field, opts...))
	}
}
func newSourceFileStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SourceFileInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, SourceFileTable, SourceFileColumn),
	)
}
