// Code generated by ent, DO NOT EDIT.

package hlsartifact

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldLTE(FieldID, id))
}

// SourceFileID applies equality check predicate on the "source_file_id" field. It's identical to SourceFileIDEQ.
func SourceFileID(v int) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldEQ(FieldSourceFileID, v))
}

// StoragePath applies equality check predicate on the "storage_path" field. It's identical to StoragePathEQ.
func StoragePath(v string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldEQ(FieldStoragePath, v))
}

// SegmentCount applies equality check predicate on the "segment_count" field. It's identical to SegmentCountEQ.
func SegmentCount(v int) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldEQ(FieldSegmentCount, v))
}

// TotalSize applies equality check predicate on the "total_size" field. It's identical to TotalSizeEQ.
func TotalSize(v int64) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldEQ(FieldTotalSize, v))
}

// Codec applies equality check predicate on the "codec" field. It's identical to CodecEQ.
func Codec(v string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldEQ(FieldCodec, v))
}

// SourceFileIDEQ applies the EQ predicate on the "source_file_id" field.
func SourceFileIDEQ(v int) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldEQ(FieldSourceFileID, v))
}

// SourceFileIDNEQ applies the NEQ predicate on the "source_file_id" field.
func SourceFileIDNEQ(v int) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldNEQ(FieldSourceFileID, v))
}

// SourceFileIDIn applies the In predicate on the "source_file_id" field.
func SourceFileIDIn(vs ...int) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldIn(FieldSourceFileID, vs...))
}

// SourceFileIDNotIn applies the NotIn predicate on the "source_file_id" field.
func SourceFileIDNotIn(vs ...int) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldNotIn(FieldSourceFileID, vs...))
}

// StoragePathEQ applies the EQ predicate on the "storage_path" field.
func StoragePathEQ(v string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldEQ(FieldStoragePath, v))
}

// StoragePathNEQ applies the NEQ predicate on the "storage_path" field.
func StoragePathNEQ(v string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldNEQ(FieldStoragePath, v))
}

// StoragePathIn applies the In predicate on the "storage_path" field.
func StoragePathIn(vs ...string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldIn(FieldStoragePath, vs...))
}

// StoragePathNotIn applies the NotIn predicate on the "storage_path" field.
func StoragePathNotIn(vs ...string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldNotIn(FieldStoragePath, vs...))
}

// StoragePathGT applies the GT predicate on the "storage_path" field.
func StoragePathGT(v string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldGT(FieldStoragePath, v))
}

// StoragePathGTE applies the GTE predicate on the "storage_path" field.
func StoragePathGTE(v string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldGTE(FieldStoragePath, v))
}

// StoragePathLT applies the LT predicate on the "storage_path" field.
func StoragePathLT(v string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldLT(FieldStoragePath, v))
}

// StoragePathLTE applies the LTE predicate on the "storage_path" field.
func StoragePathLTE(v string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldLTE(FieldStoragePath, v))
}

// StoragePathContains applies the Contains predicate on the "storage_path" field.
func StoragePathContains(v string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldContains(FieldStoragePath, v))
}

// StoragePathHasPrefix applies the HasPrefix predicate on the "storage_path" field.
func StoragePathHasPrefix(v string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldHasPrefix(FieldStoragePath, v))
}

// StoragePathHasSuffix applies the HasSuffix predicate on the "storage_path" field.
func StoragePathHasSuffix(v string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldHasSuffix(FieldStoragePath, v))
}

// StoragePathEqualFold applies the EqualFold predicate on the "storage_path" field.
func StoragePathEqualFold(v string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldEqualFold(FieldStoragePath, v))
}

// StoragePathContainsFold applies the ContainsFold predicate on the "storage_path" field.
func StoragePathContainsFold(v string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldContainsFold(FieldStoragePath, v))
}

// SegmentCountEQ applies the EQ predicate on the "segment_count" field.
func SegmentCountEQ(v int) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldEQ(FieldSegmentCount, v))
}

// SegmentCountNEQ applies the NEQ predicate on the "segment_count" field.
func SegmentCountNEQ(v int) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldNEQ(FieldSegmentCount, v))
}

// SegmentCountIn applies the In predicate on the "segment_count" field.
func SegmentCountIn(vs ...int) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldIn(FieldSegmentCount, vs...))
}

// SegmentCountNotIn applies the NotIn predicate on the "segment_count" field.
func SegmentCountNotIn(vs ...int) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldNotIn(FieldSegmentCount, vs...))
}

// SegmentCountGT applies the GT predicate on the "segment_count" field.
func SegmentCountGT(v int) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldGT(FieldSegmentCount, v))
}

// SegmentCountGTE applies the GTE predicate on the "segment_count" field.
func SegmentCountGTE(v int) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldGTE(FieldSegmentCount, v))
}

// SegmentCountLT applies the LT predicate on the "segment_count" field.
func SegmentCountLT(v int) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldLT(FieldSegmentCount, v))
}

// SegmentCountLTE applies the LTE predicate on the "segment_count" field.
func SegmentCountLTE(v int) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldLTE(FieldSegmentCount, v))
}

// TotalSizeEQ applies the EQ predicate on the "total_size" field.
func TotalSizeEQ(v int64) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldEQ(FieldTotalSize, v))
}

// TotalSizeNEQ applies the NEQ predicate on the "total_size" field.
func TotalSizeNEQ(v int64) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldNEQ(FieldTotalSize, v))
}

// TotalSizeIn applies the In predicate on the "total_size" field.
func TotalSizeIn(vs ...int64) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldIn(FieldTotalSize, vs...))
}

// TotalSizeNotIn applies the NotIn predicate on the "total_size" field.
func TotalSizeNotIn(vs ...int64) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldNotIn(FieldTotalSize, vs...))
}

// TotalSizeGT applies the GT predicate on the "total_size" field.
func TotalSizeGT(v int64) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldGT(FieldTotalSize, v))
}

// TotalSizeGTE applies the GTE predicate on the "total_size" field.
func TotalSizeGTE(v int64) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldGTE(FieldTotalSize, v))
}

// TotalSizeLT applies the LT predicate on the "total_size" field.
func TotalSizeLT(v int64) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldLT(FieldTotalSize, v))
}

// TotalSizeLTE applies the LTE predicate on the "total_size" field.
func TotalSizeLTE(v int64) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldLTE(FieldTotalSize, v))
}

// CodecEQ applies the EQ predicate on the "codec" field.
func CodecEQ(v string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldEQ(FieldCodec, v))
}

// CodecNEQ applies the NEQ predicate on the "codec" field.
func CodecNEQ(v string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldNEQ(FieldCodec, v))
}

// CodecIn applies the In predicate on the "codec" field.
func CodecIn(vs ...string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldIn(FieldCodec, vs...))
}

// CodecNotIn applies the NotIn predicate on the "codec" field.
func CodecNotIn(vs ...string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldNotIn(FieldCodec, vs...))
}

// CodecGT applies the GT predicate on the "codec" field.
func CodecGT(v string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldGT(FieldCodec, v))
}

// CodecGTE applies the GTE predicate on the "codec" field.
func CodecGTE(v string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldGTE(FieldCodec, v))
}

// CodecLT applies the LT predicate on the "codec" field.
func CodecLT(v string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldLT(FieldCodec, v))
}

// CodecLTE applies the LTE predicate on the "codec" field.
func CodecLTE(v string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldLTE(FieldCodec, v))
}

// CodecContains applies the Contains predicate on the "codec" field.
func CodecContains(v string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldContains(FieldCodec, v))
}

// CodecHasPrefix applies the HasPrefix predicate on the "codec" field.
func CodecHasPrefix(v string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldHasPrefix(FieldCodec, v))
}

// CodecHasSuffix applies the HasSuffix predicate on the "codec" field.
func CodecHasSuffix(v string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldHasSuffix(FieldCodec, v))
}

// CodecEqualFold applies the EqualFold predicate on the "codec" field.
func CodecEqualFold(v string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldEqualFold(FieldCodec, v))
}

// CodecContainsFold applies the ContainsFold predicate on the "codec" field.
func CodecContainsFold(v string) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.FieldContainsFold(FieldCodec, v))
}

// HasSourceFile applies the HasEdge predicate on the "source_file" edge.
func HasSourceFile() predicate.HLSArtifact {
	return predicate.HLSArtifact(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, SourceFileTable, SourceFileColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceFileWith applies the HasEdge predicate on the "source_file" edge with a given conditions (other predicates).
func HasSourceFileWith(preds ...predicate.File) predicate.HLSArtifact {
	return predicate.HLSArtifact(func(s *sql.Selector) {
		step := newSourceFileStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.HLSArtifact) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.HLSArtifact) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.HLSArtifact) predicate.HLSArtifact {
	return predicate.HLSArtifact(sql.NotPredicates(p))
}
