// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/hlsartifact"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// HLSArtifactDelete is the builder for deleting a HLSArtifact entity.
type HLSArtifactDelete struct {
	config
	hooks    []Hook
	mutation *HLSArtifactMutation
}

// Where appends a list predicates to the HLSArtifactDelete builder.
func (had *HLSArtifactDelete) Where(ps ...predicate.HLSArtifact) *HLSArtifactDelete {
	had.mutation.Where(ps...)
	return had
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (had *HLSArtifactDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, had.sqlExec, had.mutation, had.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (had *HLSArtifactDelete) ExecX(ctx context.Context) int {
	n, err := had.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (had *HLSArtifactDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(hlsartifact.Table, sqlgraph.NewFieldSpec(hlsartifact.FieldID, field.TypeInt))
	if ps := had.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, had.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	had.mutation.done = true
	return affected, err
}

// HLSArtifactDeleteOne is the builder for deleting a single HLSArtifact entity.
type HLSArtifactDeleteOne struct {
	had *HLSArtifactDelete
}

// Where appends a list predicates to the HLSArtifactDelete builder.
func (hado *HLSArtifactDeleteOne) Where(ps ...predicate.HLSArtifact) *HLSArtifactDeleteOne {
	hado.had.mutation.Where(ps...)
	return hado
}

// Exec executes the deletion query.
func (hado *HLSArtifactDeleteOne) Exec(ctx context.Context) error {
	n, err := hado.had.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{hlsartifact.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (hado *HLSArtifactDeleteOne) ExecX(ctx context.Context) {
	if err := hado.Exec(ctx); err != nil {
		panic(err)
	}
}
