// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/file"
	"github.com/cloudreve/Cloudreve/v4/ent/hlsartifact"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// HLSArtifactUpdate is the builder for updating HLSArtifact entities.
type HLSArtifactUpdate struct {
	config
	hooks    []Hook
	mutation *HLSArtifactMutation
}

// Where appends a list predicates to the HLSArtifactUpdate builder.
func (hau *HLSArtifactUpdate) Where(ps ...predicate.HLSArtifact) *HLSArtifactUpdate {
	hau.mutation.Where(ps...)
	return hau
}

// SetSourceFileID sets the "source_file_id" field.
func (hau *HLSArtifactUpdate) SetSourceFileID(i int) *HLSArtifactUpdate {
	hau.mutation.SetSourceFileID(i)
	return hau
}

// SetNillableSourceFileID sets the "source_file_id" field if the given value is not nil.
func (hau *HLSArtifactUpdate) SetNillableSourceFileID(i *int) *HLSArtifactUpdate {
	if i != nil {
		hau.SetSourceFileID(*i)
	}
	return hau
}

// SetStoragePath sets the "storage_path" field.
func (hau *HLSArtifactUpdate) SetStoragePath(s string) *HLSArtifactUpdate {
	hau.mutation.SetStoragePath(s)
	return hau
}

// SetNillableStoragePath sets the "storage_path" field if the given value is not nil.
func (hau *HLSArtifactUpdate) SetNillableStoragePath(s *string) *HLSArtifactUpdate {
	if s != nil {
		hau.SetStoragePath(*s)
	}
	return hau
}

// SetSegmentCount sets the "segment_count" field.
func (hau *HLSArtifactUpdate) SetSegmentCount(i int) *HLSArtifactUpdate {
	hau.mutation.ResetSegmentCount()
	hau.mutation.SetSegmentCount(i)
	return hau
}

// SetNillableSegmentCount sets the "segment_count" field if the given value is not nil.
func (hau *HLSArtifactUpdate) SetNillableSegmentCount(i *int) *HLSArtifactUpdate {
	if i != nil {
		hau.SetSegmentCount(*i)
	}
	return hau
}

// AddSegmentCount adds i to the "segment_count" field.
func (hau *HLSArtifactUpdate) AddSegmentCount(i int) *HLSArtifactUpdate {
	hau.mutation.AddSegmentCount(i)
	return hau
}

// SetTotalSize sets the "total_size" field.
func (hau *HLSArtifactUpdate) SetTotalSize(i int64) *HLSArtifactUpdate {
	hau.mutation.ResetTotalSize()
	hau.mutation.SetTotalSize(i)
	return hau
}

// SetNillableTotalSize sets the "total_size" field if the given value is not nil.
func (hau *HLSArtifactUpdate) SetNillableTotalSize(i *int64) *HLSArtifactUpdate {
	if i != nil {
		hau.SetTotalSize(*i)
	}
	return hau
}

// AddTotalSize adds i to the "total_size" field.
func (hau *HLSArtifactUpdate) AddTotalSize(i int64) *HLSArtifactUpdate {
	hau.mutation.AddTotalSize(i)
	return hau
}

// SetCodec sets the "codec" field.
func (hau *HLSArtifactUpdate) SetCodec(s string) *HLSArtifactUpdate {
	hau.mutation.SetCodec(s)
	return hau
}

// SetNillableCodec sets the "codec" field if the given value is not nil.
func (hau *HLSArtifactUpdate) SetNillableCodec(s *string) *HLSArtifactUpdate {
	if s != nil {
		hau.SetCodec(*s)
	}
	return hau
}

// SetSourceFile sets the "source_file" edge to the File entity.
func (hau *HLSArtifactUpdate) SetSourceFile(f *File) *HLSArtifactUpdate {
	return hau.SetSourceFileID(f.ID)
}

// Mutation returns the HLSArtifactMutation object of the builder.
func (hau *HLSArtifactUpdate) Mutation() *HLSArtifactMutation {
	return hau.mutation
}

// ClearSourceFile clears the "source_file" edge to the File entity.
func (hau *HLSArtifactUpdate) ClearSourceFile() *HLSArtifactUpdate {
	hau.mutation.ClearSourceFile()
	return hau
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (hau *HLSArtifactUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, hau.sqlSave, hau.mutation, hau.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (hau *HLSArtifactUpdate) SaveX(ctx context.Context) int {
	affected, err := hau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (hau *HLSArtifactUpdate) Exec(ctx context.Context) error {
	_, err := hau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hau *HLSArtifactUpdate) ExecX(ctx context.Context) {
	if err := hau.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hau *HLSArtifactUpdate) check() error {
	if _, ok := hau.mutation.SourceFileID(); hau.mutation.SourceFileCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "HLSArtifact.source_file"`)
	}
	return nil
}

func (hau *HLSArtifactUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := hau.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(hlsartifact.Table, hlsartifact.Columns, sqlgraph.NewFieldSpec(hlsartifact.FieldID, field.TypeInt))
	if ps := hau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := hau.mutation.StoragePath(); ok {
		_spec.SetField(hlsartifact.FieldStoragePath, field.TypeString, value)
	}
	if value, ok := hau.mutation.SegmentCount(); ok {
		_spec.SetField(hlsartifact.FieldSegmentCount, field.TypeInt, value)
	}
	if value, ok := hau.mutation.AddedSegmentCount(); ok {
		_spec.AddField(hlsartifact.FieldSegmentCount, field.TypeInt, value)
	}
	if value, ok := hau.mutation.TotalSize(); ok {
		_spec.SetField(hlsartifact.FieldTotalSize, field.TypeInt64, value)
	}
	if value, ok := hau.mutation.AddedTotalSize(); ok {
		_spec.AddField(hlsartifact.FieldTotalSize, field.TypeInt64, value)
	}
	if value, ok := hau.mutation.Codec(); ok {
		_spec.SetField(hlsartifact.FieldCodec, field.TypeString, value)
	}
	if hau.mutation.SourceFileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   hlsartifact.SourceFileTable,
			Columns: []string{hlsartifact.SourceFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := hau.mutation.SourceFileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   hlsartifact.SourceFileTable,
			Columns: []string{hlsartifact.SourceFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, hau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hlsartifact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	hau.mutation.done = true
	return n, nil
}

// HLSArtifactUpdateOne is the builder for updating a single HLSArtifact entity.
type HLSArtifactUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HLSArtifactMutation
}

// SetSourceFileID sets the "source_file_id" field.
func (hauo *HLSArtifactUpdateOne) SetSourceFileID(i int) *HLSArtifactUpdateOne {
	hauo.mutation.SetSourceFileID(i)
	return hauo
}

// SetNillableSourceFileID sets the "source_file_id" field if the given value is not nil.
func (hauo *HLSArtifactUpdateOne) SetNillableSourceFileID(i *int) *HLSArtifactUpdateOne {
	if i != nil {
		hauo.SetSourceFileID(*i)
	}
	return hauo
}

// SetStoragePath sets the "storage_path" field.
func (hauo *HLSArtifactUpdateOne) SetStoragePath(s string) *HLSArtifactUpdateOne {
	hauo.mutation.SetStoragePath(s)
	return hauo
}

// SetNillableStoragePath sets the "storage_path" field if the given value is not nil.
func (hauo *HLSArtifactUpdateOne) SetNillableStoragePath(s *string) *HLSArtifactUpdateOne {
	if s != nil {
		hauo.SetStoragePath(*s)
	}
	return hauo
}

// SetSegmentCount sets the "segment_count" field.
func (hauo *HLSArtifactUpdateOne) SetSegmentCount(i int) *HLSArtifactUpdateOne {
	hauo.mutation.ResetSegmentCount()
	hauo.mutation.SetSegmentCount(i)
	return hauo
}

// SetNillableSegmentCount sets the "segment_count" field if the given value is not nil.
func (hauo *HLSArtifactUpdateOne) SetNillableSegmentCount(i *int) *HLSArtifactUpdateOne {
	if i != nil {
		hauo.SetSegmentCount(*i)
	}
	return hauo
}

// AddSegmentCount adds i to the "segment_count" field.
func (hauo *HLSArtifactUpdateOne) AddSegmentCount(i int) *HLSArtifactUpdateOne {
	hauo.mutation.AddSegmentCount(i)
	return hauo
}

// SetTotalSize sets the "total_size" field.
func (hauo *HLSArtifactUpdateOne) SetTotalSize(i int64) *HLSArtifactUpdateOne {
	hauo.mutation.ResetTotalSize()
	hauo.mutation.SetTotalSize(i)
	return hauo
}

// SetNillableTotalSize sets the "total_size" field if the given value is not nil.
func (hauo *HLSArtifactUpdateOne) SetNillableTotalSize(i *int64) *HLSArtifactUpdateOne {
	if i != nil {
		hauo.SetTotalSize(*i)
	}
	return hauo
}

// AddTotalSize adds i to the "total_size" field.
func (hauo *HLSArtifactUpdateOne) AddTotalSize(i int64) *HLSArtifactUpdateOne {
	hauo.mutation.AddTotalSize(i)
	return hauo
}

// SetCodec sets the "codec" field.
func (hauo *HLSArtifactUpdateOne) SetCodec(s string) *HLSArtifactUpdateOne {
	hauo.mutation.SetCodec(s)
	return hauo
}

// SetNillableCodec sets the "codec" field if the given value is not nil.
func (hauo *HLSArtifactUpdateOne) SetNillableCodec(s *string) *HLSArtifactUpdateOne {
	if s != nil {
		hauo.SetCodec(*s)
	}
	return hauo
}

// SetSourceFile sets the "source_file" edge to the File entity.
func (hauo *HLSArtifactUpdateOne) SetSourceFile(f *File) *HLSArtifactUpdateOne {
	return hauo.SetSourceFileID(f.ID)
}

// Mutation returns the HLSArtifactMutation object of the builder.
func (hauo *HLSArtifactUpdateOne) Mutation() *HLSArtifactMutation {
	return hauo.mutation
}

// ClearSourceFile clears the "source_file" edge to the File entity.
func (hauo *HLSArtifactUpdateOne) ClearSourceFile() *HLSArtifactUpdateOne {
	hauo.mutation.ClearSourceFile()
	return hauo
}

// Where appends a list predicates to the HLSArtifactUpdate builder.
func (hauo *HLSArtifactUpdateOne) Where(ps ...predicate.HLSArtifact) *HLSArtifactUpdateOne {
	hauo.mutation.Where(ps...)
	return hauo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (hauo *HLSArtifactUpdateOne) Select(field string, fields ...string) *HLSArtifactUpdateOne {
	hauo.fields = append([]string{field}, fields...)
	return hauo
}

// Save executes the query and returns the updated HLSArtifact entity.
func (hauo *HLSArtifactUpdateOne) Save(ctx context.Context) (*HLSArtifact, error) {
	return withHooks(ctx, hauo.sqlSave, hauo.mutation, hauo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (hauo *HLSArtifactUpdateOne) SaveX(ctx context.Context) *HLSArtifact {
	node, err := hauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (hauo *HLSArtifactUpdateOne) Exec(ctx context.Context) error {
	_, err := hauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hauo *HLSArtifactUpdateOne) ExecX(ctx context.Context) {
	if err := hauo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hauo *HLSArtifactUpdateOne) check() error {
	if _, ok := hauo.mutation.SourceFileID(); hauo.mutation.SourceFileCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "HLSArtifact.source_file"`)
	}
	return nil
}

func (hauo *HLSArtifactUpdateOne) sqlSave(ctx context.Context) (_node *HLSArtifact, err error) {
	if err := hauo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(hlsartifact.Table, hlsartifact.Columns, sqlgraph.NewFieldSpec(hlsartifact.FieldID, field.TypeInt))
	id, ok := hauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "HLSArtifact.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := hauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hlsartifact.FieldID)
		for _, f := range fields {
			if !hlsartifact.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != hlsartifact.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := hauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := hauo.mutation.StoragePath(); ok {
		_spec.SetField(hlsartifact.FieldStoragePath, field.TypeString, value)
	}
	if value, ok := hauo.mutation.SegmentCount(); ok {
		_spec.SetField(hlsartifact.FieldSegmentCount, field.TypeInt, value)
	}
	if value, ok := hauo.mutation.AddedSegmentCount(); ok {
		_spec.AddField(hlsartifact.FieldSegmentCount, field.TypeInt, value)
	}
	if value, ok := hauo.mutation.TotalSize(); ok {
		_spec.SetField(hlsartifact.FieldTotalSize, field.TypeInt64, value)
	}
	if value, ok := hauo.mutation.AddedTotalSize(); ok {
		_spec.AddField(hlsartifact.FieldTotalSize, field.TypeInt64, value)
	}
	if value, ok := hauo.mutation.Codec(); ok {
		_spec.SetField(hlsartifact.FieldCodec, field.TypeString, value)
	}
	if hauo.mutation.SourceFileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   hlsartifact.SourceFileTable,
			Columns: []string{hlsartifact.SourceFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := hauo.mutation.SourceFileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   hlsartifact.SourceFileTable,
			Columns: []string{hlsartifact.SourceFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &HLSArtifact{config: hauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, hauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hlsartifact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	hauo.mutation.done = true
	return _node, nil
}
