// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/file"
	"github.com/cloudreve/Cloudreve/v4/ent/hlsartifact"
)

// HLSArtifactCreate is the builder for creating a HLSArtifact entity.
type HLSArtifactCreate struct {
	config
	mutation *HLSArtifactMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSourceFileID sets the "source_file_id" field.
func (hac *HLSArtifactCreate) SetSourceFileID(i int) *HLSArtifactCreate {
	hac.mutation.SetSourceFileID(i)
	return hac
}

// SetStoragePath sets the "storage_path" field.
func (hac *HLSArtifactCreate) SetStoragePath(s string) *HLSArtifactCreate {
	hac.mutation.SetStoragePath(s)
	return hac
}

// SetSegmentCount sets the "segment_count" field.
func (hac *HLSArtifactCreate) SetSegmentCount(i int) *HLSArtifactCreate {
	hac.mutation.SetSegmentCount(i)
	return hac
}

// SetNillableSegmentCount sets the "segment_count" field if the given value is not nil.
func (hac *HLSArtifactCreate) SetNillableSegmentCount(i *int) *HLSArtifactCreate {
	if i != nil {
		hac.SetSegmentCount(*i)
	}
	return hac
}

// SetTotalSize sets the "total_size" field.
func (hac *HLSArtifactCreate) SetTotalSize(i int64) *HLSArtifactCreate {
	hac.mutation.SetTotalSize(i)
	return hac
}

// SetNillableTotalSize sets the "total_size" field if the given value is not nil.
func (hac *HLSArtifactCreate) SetNillableTotalSize(i *int64) *HLSArtifactCreate {
	if i != nil {
		hac.SetTotalSize(*i)
	}
	return hac
}

// SetCodec sets the "codec" field.
func (hac *HLSArtifactCreate) SetCodec(s string) *HLSArtifactCreate {
	hac.mutation.SetCodec(s)
	return hac
}

// SetNillableCodec sets the "codec" field if the given value is not nil.
func (hac *HLSArtifactCreate) SetNillableCodec(s *string) *HLSArtifactCreate {
	if s != nil {
		hac.SetCodec(*s)
	}
	return hac
}

// SetSourceFile sets the "source_file" edge to the File entity.
func (hac *HLSArtifactCreate) SetSourceFile(f *File) *HLSArtifactCreate {
	return hac.SetSourceFileID(f.ID)
}

// Mutation returns the HLSArtifactMutation object of the builder.
func (hac *HLSArtifactCreate) Mutation() *HLSArtifactMutation {
	return hac.mutation
}

// Save creates the HLSArtifact in the database.
func (hac *HLSArtifactCreate) Save(ctx context.Context) (*HLSArtifact, error) {
	hac.defaults()
	return withHooks(ctx, hac.sqlSave, hac.mutation, hac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (hac *HLSArtifactCreate) SaveX(ctx context.Context) *HLSArtifact {
	v, err := hac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hac *HLSArtifactCreate) Exec(ctx context.Context) error {
	_, err := hac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hac *HLSArtifactCreate) ExecX(ctx context.Context) {
	if err := hac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (hac *HLSArtifactCreate) defaults() {
	if _, ok := hac.mutation.SegmentCount(); !ok {
		v := hlsartifact.DefaultSegmentCount
		hac.mutation.SetSegmentCount(v)
	}
	if _, ok := hac.mutation.TotalSize(); !ok {
		v := hlsartifact.DefaultTotalSize
		hac.mutation.SetTotalSize(v)
	}
	if _, ok := hac.mutation.Codec(); !ok {
		v := hlsartifact.DefaultCodec
		hac.mutation.SetCodec(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hac *HLSArtifactCreate) check() error {
	if _, ok := hac.mutation.SourceFileID(); !ok {
		return &ValidationError{Name: "source_file_id", err: errors.New(`ent: missing required field "HLSArtifact.source_file_id"`)}
	}
	if _, ok := hac.mutation.StoragePath(); !ok {
		return &ValidationError{Name: "storage_path", err: errors.New(`ent: missing required field "HLSArtifact.storage_path"`)}
	}
	if _, ok := hac.mutation.SegmentCount(); !ok {
		return &ValidationError{Name: "segment_count", err: errors.New(`ent: missing required field "HLSArtifact.segment_count"`)}
	}
	if _, ok := hac.mutation.TotalSize(); !ok {
		return &ValidationError{Name: "total_size", err: errors.New(`ent: missing required field "HLSArtifact.total_size"`)}
	}
	if _, ok := hac.mutation.Codec(); !ok {
		return &ValidationError{Name: "codec", err: errors.New(`ent: missing required field "HLSArtifact.codec"`)}
	}
	if _, ok := hac.mutation.SourceFileID(); !ok {
		return &ValidationError{Name: "source_file", err: errors.New(`ent: missing required edge "HLSArtifact.source_file"`)}
	}
	return nil
}

func (hac *HLSArtifactCreate) sqlSave(ctx context.Context) (*HLSArtifact, error) {
	if err := hac.check(); err != nil {
		return nil, err
	}
	_node, _spec := hac.createSpec()
	if err := sqlgraph.CreateNode(ctx, hac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	hac.mutation.id = &_node.ID
	hac.mutation.done = true
	return _node, nil
}

func (hac *HLSArtifactCreate) createSpec() (*HLSArtifact, *sqlgraph.CreateSpec) {
	var (
		_node = &HLSArtifact{config: hac.config}
		_spec = sqlgraph.NewCreateSpec(hlsartifact.Table, sqlgraph.NewFieldSpec(hlsartifact.FieldID, field.TypeInt))
	)

	if id, ok := hac.mutation.ID(); ok {
		_node.ID = id
		id64 := int64(id)
		_spec.ID.Value = id64
	}

	_spec.OnConflict = hac.conflict
	if value, ok := hac.mutation.StoragePath(); ok {
		_spec.SetField(hlsartifact.FieldStoragePath, field.TypeString, value)
		_node.StoragePath = value
	}
	if value, ok := hac.mutation.SegmentCount(); ok {
		_spec.SetField(hlsartifact.FieldSegmentCount, field.TypeInt, value)
		_node.SegmentCount = value
	}
	if value, ok := hac.mutation.TotalSize(); ok {
		_spec.SetField(hlsartifact.FieldTotalSize, field.TypeInt64, value)
		_node.TotalSize = value
	}
	if value, ok := hac.mutation.Codec(); ok {
		_spec.SetField(hlsartifact.FieldCodec, field.TypeString, value)
		_node.Codec = value
	}
	if nodes := hac.mutation.SourceFileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   hlsartifact.SourceFileTable,
			Columns: []string{hlsartifact.SourceFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SourceFileID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.HLSArtifact.Create().
//		SetSourceFileID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HLSArtifactUpsert) {
//			SetSourceFileID(v+v).
//		}).
//		Exec(ctx)
func (hac *HLSArtifactCreate) OnConflict(opts ...sql.ConflictOption) *HLSArtifactUpsertOne {
	hac.conflict = opts
	return &HLSArtifactUpsertOne{
		create: hac,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.HLSArtifact.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (hac *HLSArtifactCreate) OnConflictColumns(columns ...string) *HLSArtifactUpsertOne {
	hac.conflict = append(hac.conflict, sql.ConflictColumns(columns...))
	return &HLSArtifactUpsertOne{
		create: hac,
	}
}

type (
	// HLSArtifactUpsertOne is the builder for "upsert"-ing
	//  one HLSArtifact node.
	HLSArtifactUpsertOne struct {
		create *HLSArtifactCreate
	}

	// HLSArtifactUpsert is the "OnConflict" setter.
	HLSArtifactUpsert struct {
		*sql.UpdateSet
	}
)

// SetSourceFileID sets the "source_file_id" field.
func (u *HLSArtifactUpsert) SetSourceFileID(v int) *HLSArtifactUpsert {
	u.Set(hlsartifact.FieldSourceFileID, v)
	return u
}

// UpdateSourceFileID sets the "source_file_id" field to the value that was provided on create.
func (u *HLSArtifactUpsert) UpdateSourceFileID() *HLSArtifactUpsert {
	u.SetExcluded(hlsartifact.FieldSourceFileID)
	return u
}

// SetStoragePath sets the "storage_path" field.
func (u *HLSArtifactUpsert) SetStoragePath(v string) *HLSArtifactUpsert {
	u.Set(hlsartifact.FieldStoragePath, v)
	return u
}

// UpdateStoragePath sets the "storage_path" field to the value that was provided on create.
func (u *HLSArtifactUpsert) UpdateStoragePath() *HLSArtifactUpsert {
	u.SetExcluded(hlsartifact.FieldStoragePath)
	return u
}

// SetSegmentCount sets the "segment_count" field.
func (u *HLSArtifactUpsert) SetSegmentCount(v int) *HLSArtifactUpsert {
	u.Set(hlsartifact.FieldSegmentCount, v)
	return u
}

// UpdateSegmentCount sets the "segment_count" field to the value that was provided on create.
func (u *HLSArtifactUpsert) UpdateSegmentCount() *HLSArtifactUpsert {
	u.SetExcluded(hlsartifact.FieldSegmentCount)
	return u
}

// AddSegmentCount adds v to the "segment_count" field.
func (u *HLSArtifactUpsert) AddSegmentCount(v int) *HLSArtifactUpsert {
	u.Add(hlsartifact.FieldSegmentCount, v)
	return u
}

// SetTotalSize sets the "total_size" field.
func (u *HLSArtifactUpsert) SetTotalSize(v int64) *HLSArtifactUpsert {
	u.Set(hlsartifact.FieldTotalSize, v)
	return u
}

// UpdateTotalSize sets the "total_size" field to the value that was provided on create.
func (u *HLSArtifactUpsert) UpdateTotalSize() *HLSArtifactUpsert {
	u.SetExcluded(hlsartifact.FieldTotalSize)
	return u
}

// AddTotalSize adds v to the "total_size" field.
func (u *HLSArtifactUpsert) AddTotalSize(v int64) *HLSArtifactUpsert {
	u.Add(hlsartifact.FieldTotalSize, v)
	return u
}

// SetCodec sets the "codec" field.
func (u *HLSArtifactUpsert) SetCodec(v string) *HLSArtifactUpsert {
	u.Set(hlsartifact.FieldCodec, v)
	return u
}

// UpdateCodec sets the "codec" field to the value that was provided on create.
func (u *HLSArtifactUpsert) UpdateCodec() *HLSArtifactUpsert {
	u.SetExcluded(hlsartifact.FieldCodec)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.HLSArtifact.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *HLSArtifactUpsertOne) UpdateNewValues() *HLSArtifactUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.HLSArtifact.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *HLSArtifactUpsertOne) Ignore() *HLSArtifactUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HLSArtifactUpsertOne) DoNothing() *HLSArtifactUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HLSArtifactCreate.OnConflict
// documentation for more info.
func (u *HLSArtifactUpsertOne) Update(set func(*HLSArtifactUpsert)) *HLSArtifactUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HLSArtifactUpsert{UpdateSet: update})
	}))
	return u
}

// SetSourceFileID sets the "source_file_id" field.
func (u *HLSArtifactUpsertOne) SetSourceFileID(v int) *HLSArtifactUpsertOne {
	return u.Update(func(s *HLSArtifactUpsert) {
		s.SetSourceFileID(v)
	})
}

// UpdateSourceFileID sets the "source_file_id" field to the value that was provided on create.
func (u *HLSArtifactUpsertOne) UpdateSourceFileID() *HLSArtifactUpsertOne {
	return u.Update(func(s *HLSArtifactUpsert) {
		s.UpdateSourceFileID()
	})
}

// SetStoragePath sets the "storage_path" field.
func (u *HLSArtifactUpsertOne) SetStoragePath(v string) *HLSArtifactUpsertOne {
	return u.Update(func(s *HLSArtifactUpsert) {
		s.SetStoragePath(v)
	})
}

// UpdateStoragePath sets the "storage_path" field to the value that was provided on create.
func (u *HLSArtifactUpsertOne) UpdateStoragePath() *HLSArtifactUpsertOne {
	return u.Update(func(s *HLSArtifactUpsert) {
		s.UpdateStoragePath()
	})
}

// SetSegmentCount sets the "segment_count" field.
func (u *HLSArtifactUpsertOne) SetSegmentCount(v int) *HLSArtifactUpsertOne {
	return u.Update(func(s *HLSArtifactUpsert) {
		s.SetSegmentCount(v)
	})
}

// AddSegmentCount adds v to the "segment_count" field.
func (u *HLSArtifactUpsertOne) AddSegmentCount(v int) *HLSArtifactUpsertOne {
	return u.Update(func(s *HLSArtifactUpsert) {
		s.AddSegmentCount(v)
	})
}

// UpdateSegmentCount sets the "segment_count" field to the value that was provided on create.
func (u *HLSArtifactUpsertOne) UpdateSegmentCount() *HLSArtifactUpsertOne {
	return u.Update(func(s *HLSArtifactUpsert) {
		s.UpdateSegmentCount()
	})
}

// SetTotalSize sets the "total_size" field.
func (u *HLSArtifactUpsertOne) SetTotalSize(v int64) *HLSArtifactUpsertOne {
	return u.Update(func(s *HLSArtifactUpsert) {
		s.SetTotalSize(v)
	})
}

// AddTotalSize adds v to the "total_size" field.
func (u *HLSArtifactUpsertOne) AddTotalSize(v int64) *HLSArtifactUpsertOne {
	return u.Update(func(s *HLSArtifactUpsert) {
		s.AddTotalSize(v)
	})
}

// UpdateTotalSize sets the "total_size" field to the value that was provided on create.
func (u *HLSArtifactUpsertOne) UpdateTotalSize() *HLSArtifactUpsertOne {
	return u.Update(func(s *HLSArtifactUpsert) {
		s.UpdateTotalSize()
	})
}

// SetCodec sets the "codec" field.
func (u *HLSArtifactUpsertOne) SetCodec(v string) *HLSArtifactUpsertOne {
	return u.Update(func(s *HLSArtifactUpsert) {
		s.SetCodec(v)
	})
}

// UpdateCodec sets the "codec" field to the value that was provided on create.
func (u *HLSArtifactUpsertOne) UpdateCodec() *HLSArtifactUpsertOne {
	return u.Update(func(s *HLSArtifactUpsert) {
		s.UpdateCodec()
	})
}

// Exec executes the query.
func (u *HLSArtifactUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HLSArtifactCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HLSArtifactUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *HLSArtifactUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *HLSArtifactUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (m *HLSArtifactCreate) SetRawID(t int) *HLSArtifactCreate {
	m.mutation.SetRawID(t)
	return m
}

// HLSArtifactCreateBulk is the builder for creating many HLSArtifact entities in bulk.
type HLSArtifactCreateBulk struct {
	config
	err      error
	builders []*HLSArtifactCreate
	conflict []sql.ConflictOption
}

// Save creates the HLSArtifact entities in the database.
func (hacb *HLSArtifactCreateBulk) Save(ctx context.Context) ([]*HLSArtifact, error) {
	if hacb.err != nil {
		return nil, hacb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(hacb.builders))
	nodes := make([]*HLSArtifact, len(hacb.builders))
	mutators := make([]Mutator, len(hacb.builders))
	for i := range hacb.builders {
		func(i int, root context.Context) {
			builder := hacb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HLSArtifactMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, hacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = hacb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, hacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, hacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (hacb *HLSArtifactCreateBulk) SaveX(ctx context.Context) []*HLSArtifact {
	v, err := hacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hacb *HLSArtifactCreateBulk) Exec(ctx context.Context) error {
	_, err := hacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hacb *HLSArtifactCreateBulk) ExecX(ctx context.Context) {
	if err := hacb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.HLSArtifact.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HLSArtifactUpsert) {
//			SetSourceFileID(v+v).
//		}).
//		Exec(ctx)
func (hacb *HLSArtifactCreateBulk) OnConflict(opts ...sql.ConflictOption) *HLSArtifactUpsertBulk {
	hacb.conflict = opts
	return &HLSArtifactUpsertBulk{
		create: hacb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.HLSArtifact.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (hacb *HLSArtifactCreateBulk) OnConflictColumns(columns ...string) *HLSArtifactUpsertBulk {
	hacb.conflict = append(hacb.conflict, sql.ConflictColumns(columns...))
	return &HLSArtifactUpsertBulk{
		create: hacb,
	}
}

// HLSArtifactUpsertBulk is the builder for "upsert"-ing
// a bulk of HLSArtifact nodes.
type HLSArtifactUpsertBulk struct {
	create *HLSArtifactCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.HLSArtifact.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *HLSArtifactUpsertBulk) UpdateNewValues() *HLSArtifactUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.HLSArtifact.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *HLSArtifactUpsertBulk) Ignore() *HLSArtifactUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HLSArtifactUpsertBulk) DoNothing() *HLSArtifactUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HLSArtifactCreateBulk.OnConflict
// documentation for more info.
func (u *HLSArtifactUpsertBulk) Update(set func(*HLSArtifactUpsert)) *HLSArtifactUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HLSArtifactUpsert{UpdateSet: update})
	}))
	return u
}

// SetSourceFileID sets the "source_file_id" field.
func (u *HLSArtifactUpsertBulk) SetSourceFileID(v int) *HLSArtifactUpsertBulk {
	return u.Update(func(s *HLSArtifactUpsert) {
		s.SetSourceFileID(v)
	})
}

// UpdateSourceFileID sets the "source_file_id" field to the value that was provided on create.
func (u *HLSArtifactUpsertBulk) UpdateSourceFileID() *HLSArtifactUpsertBulk {
	return u.Update(func(s *HLSArtifactUpsert) {
		s.UpdateSourceFileID()
	})
}

// SetStoragePath sets the "storage_path" field.
func (u *HLSArtifactUpsertBulk) SetStoragePath(v string) *HLSArtifactUpsertBulk {
	return u.Update(func(s *HLSArtifactUpsert) {
		s.SetStoragePath(v)
	})
}

// UpdateStoragePath sets the "storage_path" field to the value that was provided on create.
func (u *HLSArtifactUpsertBulk) UpdateStoragePath() *HLSArtifactUpsertBulk {
	return u.Update(func(s *HLSArtifactUpsert) {
		s.UpdateStoragePath()
	})
}

// SetSegmentCount sets the "segment_count" field.
func (u *HLSArtifactUpsertBulk) SetSegmentCount(v int) *HLSArtifactUpsertBulk {
	return u.Update(func(s *HLSArtifactUpsert) {
		s.SetSegmentCount(v)
	})
}

// AddSegmentCount adds v to the "segment_count" field.
func (u *HLSArtifactUpsertBulk) AddSegmentCount(v int) *HLSArtifactUpsertBulk {
	return u.Update(func(s *HLSArtifactUpsert) {
		s.AddSegmentCount(v)
	})
}

// UpdateSegmentCount sets the "segment_count" field to the value that was provided on create.
func (u *HLSArtifactUpsertBulk) UpdateSegmentCount() *HLSArtifactUpsertBulk {
	return u.Update(func(s *HLSArtifactUpsert) {
		s.UpdateSegmentCount()
	})
}

// SetTotalSize sets the "total_size" field.
func (u *HLSArtifactUpsertBulk) SetTotalSize(v int64) *HLSArtifactUpsertBulk {
	return u.Update(func(s *HLSArtifactUpsert) {
		s.SetTotalSize(v)
	})
}

// AddTotalSize adds v to the "total_size" field.
func (u *HLSArtifactUpsertBulk) AddTotalSize(v int64) *HLSArtifactUpsertBulk {
	return u.Update(func(s *HLSArtifactUpsert) {
		s.AddTotalSize(v)
	})
}

// UpdateTotalSize sets the "total_size" field to the value that was provided on create.
func (u *HLSArtifactUpsertBulk) UpdateTotalSize() *HLSArtifactUpsertBulk {
	return u.Update(func(s *HLSArtifactUpsert) {
		s.UpdateTotalSize()
	})
}

// SetCodec sets the "codec" field.
func (u *HLSArtifactUpsertBulk) SetCodec(v string) *HLSArtifactUpsertBulk {
	return u.Update(func(s *HLSArtifactUpsert) {
		s.SetCodec(v)
	})
}

// UpdateCodec sets the "codec" field to the value that was provided on create.
func (u *HLSArtifactUpsertBulk) UpdateCodec() *HLSArtifactUpsertBulk {
	return u.Update(func(s *HLSArtifactUpsert) {
		s.UpdateCodec()
	})
}

// Exec executes the query.
func (u *HLSArtifactUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the HLSArtifactCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HLSArtifactCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HLSArtifactUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
