// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/file"
	"github.com/cloudreve/Cloudreve/v4/ent/hlsartifact"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// HLSArtifactQuery is the builder for querying HLSArtifact entities.
type HLSArtifactQuery struct {
	config
	ctx            *QueryContext
	order          []hlsartifact.OrderOption
	inters         []Interceptor
	predicates     []predicate.HLSArtifact
	withSourceFile *FileQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the HLSArtifactQuery builder.
func (haq *HLSArtifactQuery) Where(ps ...predicate.HLSArtifact) *HLSArtifactQuery {
	haq.predicates = append(haq.predicates, ps...)
	return haq
}

// Limit the number of records to be returned by this query.
func (haq *HLSArtifactQuery) Limit(limit int) *HLSArtifactQuery {
	haq.ctx.Limit = &limit
	return haq
}

// Offset to start from.
func (haq *HLSArtifactQuery) Offset(offset int) *HLSArtifactQuery {
	haq.ctx.Offset = &offset
	return haq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (haq *HLSArtifactQuery) Unique(unique bool) *HLSArtifactQuery {
	haq.ctx.Unique = &unique
	return haq
}

// Order specifies how the records should be ordered.
func (haq *HLSArtifactQuery) Order(o ...hlsartifact.OrderOption) *HLSArtifactQuery {
	haq.order = append(haq.order, o...)
	return haq
}

// QuerySourceFile chains the current query on the "source_file" edge.
func (haq *HLSArtifactQuery) QuerySourceFile() *FileQuery {
	query := (&FileClient{config: haq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := haq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := haq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(hlsartifact.Table, hlsartifact.FieldID, selector),
			sqlgraph.To(file.Table, file.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, hlsartifact.SourceFileTable, hlsartifact.SourceFileColumn),
		)
		fromU = sqlgraph.SetNeighbors(haq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first HLSArtifact entity from the query.
// Returns a *NotFoundError when no HLSArtifact was found.
func (haq *HLSArtifactQuery) First(ctx context.Context) (*HLSArtifact, error) {
	nodes, err := haq.Limit(1).All(setContextOp(ctx, haq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{hlsartifact.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (haq *HLSArtifactQuery) FirstX(ctx context.Context) *HLSArtifact {
	node, err := haq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first HLSArtifact ID from the query.
// Returns a *NotFoundError when no HLSArtifact ID was found.
func (haq *HLSArtifactQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = haq.Limit(1).IDs(setContextOp(ctx, haq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{hlsartifact.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (haq *HLSArtifactQuery) FirstIDX(ctx context.Context) int {
	id, err := haq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single HLSArtifact entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one HLSArtifact entity is found.
// Returns a *NotFoundError when no HLSArtifact entities are found.
func (haq *HLSArtifactQuery) Only(ctx context.Context) (*HLSArtifact, error) {
	nodes, err := haq.Limit(2).All(setContextOp(ctx, haq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{hlsartifact.Label}
	default:
		return nil, &NotSingularError{hlsartifact.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (haq *HLSArtifactQuery) OnlyX(ctx context.Context) *HLSArtifact {
	node, err := haq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only HLSArtifact ID in the query.
// Returns a *NotSingularError when more than one HLSArtifact ID is found.
// Returns a *NotFoundError when no entities are found.
func (haq *HLSArtifactQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = haq.Limit(2).IDs(setContextOp(ctx, haq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{hlsartifact.Label}
	default:
		err = &NotSingularError{hlsartifact.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (haq *HLSArtifactQuery) OnlyIDX(ctx context.Context) int {
	id, err := haq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of HLSArtifacts.
func (haq *HLSArtifactQuery) All(ctx context.Context) ([]*HLSArtifact, error) {
	ctx = setContextOp(ctx, haq.ctx, "All")
	if err := haq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*HLSArtifact, *HLSArtifactQuery]()
	return withInterceptors[[]*HLSArtifact](ctx, haq, qr, haq.inters)
}

// AllX is like All, but panics if an error occurs.
func (haq *HLSArtifactQuery) AllX(ctx context.Context) []*HLSArtifact {
	nodes, err := haq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of HLSArtifact IDs.
func (haq *HLSArtifactQuery) IDs(ctx context.Context) (ids []int, err error) {
	if haq.ctx.Unique == nil && haq.path != nil {
		haq.Unique(true)
	}
	ctx = setContextOp(ctx, haq.ctx, "IDs")
	if err = haq.Select(hlsartifact.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (haq *HLSArtifactQuery) IDsX(ctx context.Context) []int {
	ids, err := haq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (haq *HLSArtifactQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, haq.ctx, "Count")
	if err := haq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, haq, querierCount[*HLSArtifactQuery](), haq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (haq *HLSArtifactQuery) CountX(ctx context.Context) int {
	count, err := haq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (haq *HLSArtifactQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, haq.ctx, "Exist")
	switch _, err := haq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (haq *HLSArtifactQuery) ExistX(ctx context.Context) bool {
	exist, err := haq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the HLSArtifactQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (haq *HLSArtifactQuery) Clone() *HLSArtifactQuery {
	if haq == nil {
		return nil
	}
	return &HLSArtifactQuery{
		config:         haq.config,
		ctx:            haq.ctx.Clone(),
		order:          append([]hlsartifact.OrderOption{}, haq.order...),
		inters:         append([]Interceptor{}, haq.inters...),
		predicates:     append([]predicate.HLSArtifact{}, haq.predicates...),
		withSourceFile: haq.withSourceFile.Clone(),
		// clone intermediate query.
		sql:  haq.sql.Clone(),
		path: haq.path,
	}
}

// WithSourceFile tells the query-builder to eager-load the nodes that are connected to
// the "source_file" edge. The optional arguments are used to configure the query builder of the edge.
func (haq *HLSArtifactQuery) WithSourceFile(opts ...func(*FileQuery)) *HLSArtifactQuery {
	query := (&FileClient{config: haq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	haq.withSourceFile = query
	return haq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SourceFileID int `json:"source_file_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.HLSArtifact.Query().
//		GroupBy(hlsartifact.FieldSourceFileID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (haq *HLSArtifactQuery) GroupBy(field string, fields ...string) *HLSArtifactGroupBy {
	haq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &HLSArtifactGroupBy{build: haq}
	grbuild.flds = &haq.ctx.Fields
	grbuild.label = hlsartifact.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SourceFileID int `json:"source_file_id,omitempty"`
//	}
//
//	client.HLSArtifact.Query().
//		Select(hlsartifact.FieldSourceFileID).
//		Scan(ctx, &v)
func (haq *HLSArtifactQuery) Select(fields ...string) *HLSArtifactSelect {
	haq.ctx.Fields = append(haq.ctx.Fields, fields...)
	sbuild := &HLSArtifactSelect{HLSArtifactQuery: haq}
	sbuild.label = hlsartifact.Label
	sbuild.flds, sbuild.scan = &haq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a HLSArtifactSelect configured with the given aggregations.
func (haq *HLSArtifactQuery) Aggregate(fns ...AggregateFunc) *HLSArtifactSelect {
	return haq.Select().Aggregate(fns...)
}

func (haq *HLSArtifactQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range haq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, haq); err != nil {
				return err
			}
		}
	}
	for _, f := range haq.ctx.Fields {
		if !hlsartifact.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if haq.path != nil {
		prev, err := haq.path(ctx)
		if err != nil {
			return err
		}
		haq.sql = prev
	}
	return nil
}

func (haq *HLSArtifactQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*HLSArtifact, error) {
	var (
		nodes       = []*HLSArtifact{}
		_spec       = haq.querySpec()
		loadedTypes = [1]bool{
			haq.withSourceFile != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*HLSArtifact).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &HLSArtifact{config: haq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, haq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := haq.withSourceFile; query != nil {
		if err := haq.loadSourceFile(ctx, query, nodes, nil,
			func(n *HLSArtifact, e *File) { n.Edges.SourceFile = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (haq *HLSArtifactQuery) loadSourceFile(ctx context.Context, query *FileQuery, nodes []*HLSArtifact, init func(*HLSArtifact), assign func(*HLSArtifact, *File)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*HLSArtifact)
	for i := range nodes {
		fk := nodes[i].SourceFileID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(file.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "source_file_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (haq *HLSArtifactQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := haq.querySpec()
	_spec.Node.Columns = haq.ctx.Fields
	if len(haq.ctx.Fields) > 0 {
		_spec.Unique = haq.ctx.Unique != nil && *haq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, haq.driver, _spec)
}

func (haq *HLSArtifactQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(hlsartifact.Table, hlsartifact.Columns, sqlgraph.NewFieldSpec(hlsartifact.FieldID, field.TypeInt))
	_spec.From = haq.sql
	if unique := haq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if haq.path != nil {
		_spec.Unique = true
	}
	if fields := haq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hlsartifact.FieldID)
		for i := range fields {
			if fields[i] != hlsartifact.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if haq.withSourceFile != nil {
			_spec.Node.AddColumnOnce(hlsartifact.FieldSourceFileID)
		}
	}
	if ps := haq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := haq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := haq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := haq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (haq *HLSArtifactQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(haq.driver.Dialect())
	t1 := builder.Table(hlsartifact.Table)
	columns := haq.ctx.Fields
	if len(columns) == 0 {
		columns = hlsartifact.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if haq.sql != nil {
		selector = haq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if haq.ctx.Unique != nil && *haq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range haq.predicates {
		p(selector)
	}
	for _, p := range haq.order {
		p(selector)
	}
	if offset := haq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := haq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// HLSArtifactGroupBy is the group-by builder for HLSArtifact entities.
type HLSArtifactGroupBy struct {
	selector
	build *HLSArtifactQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (hagb *HLSArtifactGroupBy) Aggregate(fns ...AggregateFunc) *HLSArtifactGroupBy {
	hagb.fns = append(hagb.fns, fns...)
	return hagb
}

// Scan applies the selector query and scans the result into the given value.
func (hagb *HLSArtifactGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hagb.build.ctx, "GroupBy")
	if err := hagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HLSArtifactQuery, *HLSArtifactGroupBy](ctx, hagb.build, hagb, hagb.build.inters, v)
}

func (hagb *HLSArtifactGroupBy) sqlScan(ctx context.Context, root *HLSArtifactQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(hagb.fns))
	for _, fn := range hagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*hagb.flds)+len(hagb.fns))
		for _, f := range *hagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*hagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// HLSArtifactSelect is the builder for selecting fields of HLSArtifact entities.
type HLSArtifactSelect struct {
	*HLSArtifactQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (has *HLSArtifactSelect) Aggregate(fns ...AggregateFunc) *HLSArtifactSelect {
	has.fns = append(has.fns, fns...)
	return has
}

// Scan applies the selector query and scans the result into the given value.
func (has *HLSArtifactSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, has.ctx, "Select")
	if err := has.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HLSArtifactQuery, *HLSArtifactSelect](ctx, has.HLSArtifactQuery, has, has.inters, v)
}

func (has *HLSArtifactSelect) sqlScan(ctx context.Context, root *HLSArtifactQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(has.fns))
	for _, fn := range has.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*has.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := has.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
