// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cloudreve/Cloudreve/v4/ent/file"
	"github.com/cloudreve/Cloudreve/v4/ent/hlsartifact"
)

// HLSArtifact is the model entity for the HLSArtifact schema.
type HLSArtifact struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SourceFileID holds the value of the "source_file_id" field.
	SourceFileID int `json:"source_file_id,omitempty"`
	// StoragePath holds the value of the "storage_path" field.
	StoragePath string `json:"storage_path,omitempty"`
	// SegmentCount holds the value of the "segment_count" field.
	SegmentCount int `json:"segment_count,omitempty"`
	// TotalSize holds the value of the "total_size" field.
	TotalSize int64 `json:"total_size,omitempty"`
	// Codec holds the value of the "codec" field.
	Codec string `json:"codec,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the HLSArtifactQuery when eager-loading is set.
	Edges        HLSArtifactEdges `json:"edges"`
	selectValues sql.SelectValues
}

// HLSArtifactEdges holds the relations/edges for other nodes in the graph.
type HLSArtifactEdges struct {
	// SourceFile holds the value of the source_file edge.
	SourceFile *File `json:"source_file,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SourceFileOrErr returns the SourceFile value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e HLSArtifactEdges) SourceFileOrErr() (*File, error) {
	if e.loadedTypes[0] {
		if e.SourceFile == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: file.Label}
		}
		return e.SourceFile, nil
	}
	return nil, &NotLoadedError{edge: "source_file"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*HLSArtifact) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case hlsartifact.FieldID, hlsartifact.FieldSourceFileID, hlsartifact.FieldSegmentCount, hlsartifact.FieldTotalSize:
			values[i] = new(sql.NullInt64)
		case hlsartifact.FieldStoragePath, hlsartifact.FieldCodec:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the HLSArtifact fields.
func (ha *HLSArtifact) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case hlsartifact.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ha.ID = int(value.Int64)
		case hlsartifact.FieldSourceFileID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_file_id", values[i])
			} else if value.Valid {
				ha.SourceFileID = int(value.Int64)
			}
		case hlsartifact.FieldStoragePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field storage_path", values[i])
			} else if value.Valid {
				ha.StoragePath = value.String
			}
		case hlsartifact.FieldSegmentCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field segment_count", values[i])
			} else if value.Valid {
				ha.SegmentCount = int(value.Int64)
			}
		case hlsartifact.FieldTotalSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_size", values[i])
			} else if value.Valid {
				ha.TotalSize = value.Int64
			}
		case hlsartifact.FieldCodec:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field codec", values[i])
			} else if value.Valid {
				ha.Codec = value.String
			}
		default:
			ha.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the HLSArtifact.
// This includes values selected through modifiers, order, etc.
func (ha *HLSArtifact) Value(name string) (ent.Value, error) {
	return ha.selectValues.Get(name)
}

// QuerySourceFile queries the "source_file" edge of the HLSArtifact entity.
func (ha *HLSArtifact) QuerySourceFile() *FileQuery {
	return NewHLSArtifactClient(ha.config).QuerySourceFile(ha)
}

// Update returns a builder for updating this HLSArtifact.
// Note that you need to call HLSArtifact.Unwrap() before calling this method if this HLSArtifact
// was returned from a transaction, and the transaction was committed or rolled back.
func (ha *HLSArtifact) Update() *HLSArtifactUpdateOne {
	return NewHLSArtifactClient(ha.config).UpdateOne(ha)
}

// Unwrap unwraps the HLSArtifact entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ha *HLSArtifact) Unwrap() *HLSArtifact {
	_tx, ok := ha.config.driver.(*txDriver)
	if !ok {
		panic("ent: HLSArtifact is not a transactional entity")
	}
	ha.config.driver = _tx.drv
	return ha
}

// String implements the fmt.Stringer.
func (ha *HLSArtifact) String() string {
	var builder strings.Builder
	builder.WriteString("HLSArtifact(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ha.ID))
	builder.WriteString("source_file_id=")
	builder.WriteString(fmt.Sprintf("%v", ha.SourceFileID))
	builder.WriteString(", ")
	builder.WriteString("storage_path=")
	builder.WriteString(ha.StoragePath)
	builder.WriteString(", ")
	builder.WriteString("segment_count=")
	builder.WriteString(fmt.Sprintf("%v", ha.SegmentCount))
	builder.WriteString(", ")
	builder.WriteString("total_size=")
	builder.WriteString(fmt.Sprintf("%v", ha.TotalSize))
	builder.WriteString(", ")
	builder.WriteString("codec=")
	builder.WriteString(ha.Codec)
	builder.WriteByte(')')
	return builder.String()
}

// SetSourceFile manually set the edge as loaded state.
func (e *HLSArtifact) SetSourceFile(v *File) {
	e.Edges.SourceFile = v
	e.Edges.loadedTypes[0] = true
}

// HLSArtifacts is a parsable slice of HLSArtifact.
type HLSArtifacts []*HLSArtifact
